// <auto-generated />
using System;
using CreditosCore.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CreditosCore.Migrations
{
    [DbContext(typeof(SqlDataContext))]
    partial class SqlDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.15");

            modelBuilder.Entity("CreditosCore.Controllers.Clientes.ClientesModel", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApellidoMaterno")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("Correo")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("ClienteId");

                    b.ToTable("clientes");
                });

            modelBuilder.Entity("CreditosCore.Controllers.Creditos.CreditoAmortizacionPagosModel", b =>
                {
                    b.Property<int>("CreditoAmortizacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CreditoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EstatusId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Monto")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroPago")
                        .HasColumnType("INTEGER");

                    b.HasKey("CreditoAmortizacionId");

                    b.HasIndex("CreditoId");

                    b.ToTable("creditosamortiguacion");
                });

            modelBuilder.Entity("CreditosCore.Controllers.Creditos.CreditosModel", b =>
                {
                    b.Property<int>("CreditoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ComisionFaltaPago")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DescuentoPagoFinal")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCredito")
                        .HasColumnType("Date");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Folio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontoInteres")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontoPago")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontoPrestamo")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("TEXT");

                    b.Property<int>("Plazos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoPago")
                        .HasColumnType("INTEGER");

                    b.Property<int>("idUsuario")
                        .HasColumnType("INTEGER");

                    b.HasKey("CreditoId");

                    b.ToTable("creditos");
                });

            modelBuilder.Entity("CreditosCore.Controllers.Pagos.PagosModel", b =>
                {
                    b.Property<int>("PagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CreditoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EstatusId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Monto")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("descuento")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("faltaDePago")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("fechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("fechaPago")
                        .HasColumnType("TEXT");

                    b.Property<int>("idUsuario")
                        .HasColumnType("INTEGER");

                    b.Property<string>("observacion")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("PagoId");

                    b.ToTable("pagos");
                });

            modelBuilder.Entity("CreditosCore.Controllers.Usuarios.UsuariosModel", b =>
                {
                    b.Property<int>("usuarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("apellidoPaterno")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("contra")
                        .HasColumnType("TEXT");

                    b.Property<string>("nickname")
                        .HasMaxLength(12)
                        .HasColumnType("TEXT");

                    b.Property<string>("nombre")
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ultimoInicioSesion")
                        .HasColumnType("TEXT");

                    b.HasKey("usuarioID");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("CreditosCore.Controllers.Creditos.CreditoAmortizacionPagosModel", b =>
                {
                    b.HasOne("CreditosCore.Controllers.Creditos.CreditosModel", "credito")
                        .WithMany()
                        .HasForeignKey("CreditoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("credito");
                });
#pragma warning restore 612, 618
        }
    }
}
